server:
  port: 8080
  shutdown: graceful

logging:
  level:
    com:
      soon83:
        apigateway: debug

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            message: === [API Gateway Service] Global Filter ===
            preLogger: true
            postLogger: true
      routes:
        - id: member-api-service
          uri: lb://member-api-service
          predicates:
            - Path=/member-api-service/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                message: === [Member Api Service] Logging Filter ===
                preLogger: true
                postLogger: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
