server:
  port: 8080

logging:
  level:
    com:
      soon83:
        apigatewayservice: debug

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            message: === [API Gateway Service] Global Filter ===
            preLogger: true
            postLogger: true
      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/member-service/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                message: === [Member Service] Logging Filter ===
                preLogger: true
                postLogger: true

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                message: === [Product Service] Logging Filter ===
                preLogger: true
                postLogger: true
